##生产环境
##服务端口
#server:
#  port: 8091
#  tomcat:
#    connection-timeout: 180000
#spring:
#  application:
#    name: disPart-files  #服务名
#  cloud:
#    nacos:
#      discovery:
##        server-addr: 128.11.132.1:8848
#        server-addr: 10.250.16.40:8848
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  #mysql数据库链接 om.mysql.cj.jdbc.Driver
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
##    url: jdbc:mysql://128.11.132.1:3306/logistics?charaterEncoding=utf8&useSSL=false
##    username: root
##    password: 123456
#    url: jdbc:mysql://10.250.16.38:3306/logistics?charaterEncoding=utf8&useSSL=false
#    username: deployer
#    Wpassword: mysql123
#
#  #返回json的全局时间格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
##配置mapper.xml文件的路径
#mybatis-plus:
#  mapper-locations: classpath*:com/dispart/dao/mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
#feign:
#  sentinel:
#    enabled: true
#sign:
#  secret: KTLFJDAK@543&#23234FdfdsT
#http:
#  multipart:
#    max-file-size: 10Mb #单个文件不超过10M
#    Max-request-size: 100Mb #请求文件总大小不超过100M
##文件存储路径
#fileProps:
#  downUploadPath: /home/ap/file/
#  fileUploadPath: /home/ap/file/
#  fileLinkPath: https://nptest.gnwly.cn/file  #访问地址
#
#logging:
#  file:
#    name: /home/ap/files/log/files_log.log
#
#
#qrCode:
#  width: 300
#  height: 300
#  format: png
#  #二维码内容
#  url: https://nptest.gnwly.cn?busineId=
#  #二维码下载路径
#  reqUrl: https://nptest.gnwly.cn/file/qrcode/
#  #二维码本地存放路径
#  savaPath: /home/ap/file/qrcode/
#  #log本地存放路径
#  logPath: /home/ap/file/qrcode/log/log.jpg
