###服务
#spring:
#  profiles:
#    active: dev1 #环境设置


spring:
  application:
    name: disPart-files  #服务名
  cloud:
    nacos:
      config:
        server-addr: 128.11.132.1:8848
        #        server-addr: 10.250.16.40:8848  #外网测试
        file-extension: yaml

#minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin

