#服务端口
#server:
#  port: 8088
spring:
#  application:
#    name: disPare-task #服务名
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 10.250.16.40:8848
  endpoints:
    web:
      exposure:
        include: "*"
  profiles:
    active: prod #环境设置
  freemarker:
    suffix: .ftl
#  redis:
#    host: 10.250.16.38
#    port: 6379
#    timeout: 10s
#    password: 123456
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-active: 8
#        max-wait: -1m
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  #mysql数据库链接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.250.16.38:3306/logistics?charaterEncoding=utf8&useSSL=false
    username: deployer
    password: mysql123
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mapper.xml文件的路径
mybatis-plus:
#  mapper-locations: classpath:com/disPart/dao/mapper/*.xml
#  classpath:/com/dispart/dao/auto/mapper/xml/*Mapper:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:com/disPart/dao/mapper/*Mapper.xml
feign:
  sentinel:
    enabled: true
logging.level.org.springframework.security: DEBUG
#外联区的接口地址
DISP20210099: /securityCenter/DISP20210099 #发送验证码
sign:
  secret: KTLFJDAK@543&#23234FdfdsT

#  savaPath: D:\qrCode\  #二维码本地存放路径
#  logPath: D:\qrCode\log\log.jpg  #log本地存放路径

pushUrl: http://10.250.16.35:8082

logging:
  file:
    name: /home/ap/task/log/task_log.log

out-hsb:
  url: http://10.250.16.43:8082/outHsb/securityCenter/DISP20210093

