####服务端口
##spring:
##  profiles:
##    active: dev #环境设置
#
#
#
#spring:
#  application:
#    name: disPart-base  #服务名\
#  profiles:
#   active: dev #环境设置
#  cloud:
#    nacos:
#      config:
#        server-addr: 128.11.132.1:8848
#        #        server-addr: 10.250.16.40:8848  #外网测试
#        file-extension: yaml
##        group: BASE_GROUP