server:
  port: 8092

spring:
  application:
    name: disPart-out-gn-loan

  management:
    endpoints:
      web:
        exposure:
          include: "*"
  main:
    allow-bean-definition-overriding: true

  #mysql数据库链接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://128.11.132.1:3306/logistics?charaterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mapper.xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/dispart/dao/mapper/*.xml
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  file:
    name: /home/ap/outGnloan/log/gn_loan_log.log
